### ISSUE TITLE
Documentation is missing on how to invoke for mixed Elixir/erlang projects

### ISSUE THREAD

**Issue by iilyak** [okeuday/pest#3]
I tried to use pest on a mixed project. I got following error:
```
pest/pest.erl -b src/
escript: exception error: undefined function elixir_erl:debug_info/4
```

I tried few things and none of them worked. Here is a list of my attempts:
```
> pest/pest.erl -p _build/dev/lib/ -b src/
escript: exception error: undefined function elixir_erl:debug_info/4

> elixir --eval 'IO.puts(Path.dirname(Path.dirname(:code.which(:elixir_erl))))'
/usr/local/Cellar/elixir/1.9.4/bin/../lib/elixir

> pest/pest.erl -p /usr/local/Cellar/elixir/1.9.4/bin/../lib/elixir -b src/
escript: exception error: undefined function elixir_erl:debug_info/4

> pest/pest.erl -d /usr/local/Cellar/elixir/1.9.4/bin/../lib/elixir -b src/
escript: exception error: undefined function elixir_erl:debug_info/4
```

**Comment by okeuday** [comment]
@iilyak That error is due to the elixir ebin directory not being provided to the `-p` argument.  The `-b` argument is looking for beam files, so it is best to provide the directory where your project's beam output is.  A command-line like the one below should be closer to what you need:

    > pest/pest.erl -p /usr/local/Cellar/elixir/1.9.4/bin/../lib/elixir/ebin -b _build/dev/lib/

**Comment by okeuday** [comment]
I updated the README information with more Elixir-related usage information to make the `-p` code path addition clearer for Elixir usage.  Feel free to create a new issue if you run into other problems.
